# Generated by Django 4.2.13 on 2024-08-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_urls_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='urlRDF',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка PDF'),
        ),
    ]
